
@urlPrefix = https://lively-truth-3781.us-east1.akkaserverless.app
@merchantIdRange = 1
@transactionCount = 10
@transactionIntervalMs = 5
@day = 2022-01-08T00:00:00.000Z
@merchantId = merchant-1
@fromDate = 2022-01-02T00:00:00.000Z
@toDate = 2022-01-03T00:00:00.000Z
@transactionAmount = 123.45
@transactionTimestamp = 2022-01-02T00:00:00.000Z
@transactionId = transaction-1
@service = service-1
@account = account-1

### io.aggregator.action.Frontend.GenerateTransactions

curl -XPOST -H "Content-Type: application/json" -d '{
  "merchant_id_range":{{merchantIdRange}},
  "transaction_count":{{transactionCount}},
  "transaction_interval_ms":{{transactionIntervalMs}},
  "day":"{{day}}"}'
  {{urlPrefix}}/generate-transactions

### io.aggregator.action.Frontend.CollectMerchantTotals

curl -XPOST -H "Content-Type: application/json" -d '{
  "day":"{{day}}"}'
  {{urlPrefix}}/collect-merchant-totals

### io.aggregator.view.DailyTotalsByDate.GetDailyTotalsByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/daily-totals-by-date?from_date={{fromDate}}&to_date={{toDate}}'

### io.aggregator.view.DailyTotalsByMerchant.GetDailyTotalsByMerchant

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/daily-totals-by-merchant?merchant_id={{merchantId}}'

### io.aggregator.api.Transaction.CreateTransaction

curl -XPOST -H "Content-Type: application/json" -d '{
  "transaction_amount":{{transactionAmount}},
  "merchant_id":"{{merchantId}}",
  "transaction_timestamp":"{{transactionTimestamp}}"}'
  {{urlPrefix}}/transaction/{{transactionId}}/{{service}}/{{account}}/add

### io.aggregator.api.Transaction.GetTransaction

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/transaction/{{transactionId}}/{{service}}/{{account}}'
