
# Curl commands used with VS Code REST Client extension

@urlPrefix = https://sweet-scene-6700.eu-central-1.kalix.app
@merchantIdRange = 1
@transactionCount = 1
@transactionIdFirst = 1
@transactionIdLast = 2
@transactionIntervalMs = 5
@day = 2022-03-10T01:05:00.000Z
@merchantId = merchant-1
@serviceCode = service-code-1
@accountFrom = account-from-1
@accountTo = account-to-1

### io.aggregator.action.Frontend.GenerateTransactions

curl -XPOST -H "Content-Type: application/json" -d '{
  "merchant_id_range":{{merchantIdRange}},
  "transaction_count":{{transactionCount}},
  "transaction_interval_ms":{{transactionIntervalMs}},
  "day":"{{day}}"}'
  {{urlPrefix}}/generate-transactions

### io.aggregator.action.Frontend.GenerateTransactionsSingleMerchant

curl -XPOST -H "Content-Type: application/json" -d '{
  "merchant_id":"{{merchantId}}",
  "service_code":"{{serviceCode}}",
  "account_from":"{{accountFrom}}",
  "account_to":"{{accountTo}}",
  "transaction_id_first":{{transactionIdFirst}},
  "transaction_id_last":{{transactionIdLast}},
  "transaction_interval_ms":{{transactionIntervalMs}},
  "day":"{{day}}"}'
  {{urlPrefix}}/generate-transactions-single-merchant
