
# Curl commands used with VS Code REST Client extension

@urlPrefix = https://old-boat-2936.us-east1.akkaserverless.app
@merchantId = merchant-1
@fromDate = 2022-01-01T00:00:00.000-05:00
@toDate = 2023-01-01T00:00:00.000-05:00

### io.aggregator.view.MerchantPaymentsByDate.GetMerchantPaymentsByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/merchant-payments-by-date?from_date={{fromDate}}&to_date={{toDate}}'

### io.aggregator.view.MerchantPaymentsByMerchantByDate.GetMerchantPaymentsByMerchantByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/merchant-payments-by-merchant-by-date?merchant_id={{merchantId}}&from_date={{fromDate}}&to_date={{toDate}}'
