
# Curl commands used with VS Code REST Client extension

@urlPrefix = https://sweet-scene-6700.eu-central-1.kalix.app
@merchantId = merchant-1
@fromDate = 2022-01-01T00:00:00.000-05:00
@toDate = 2023-01-01T00:00:00.000-05:00

### io.aggregator.view.MerchantPaymentsByDate.GetMerchantPaymentsByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/merchant-payments-by-date?from_date={{fromDate}}&to_date={{toDate}}'

### io.aggregator.view.MerchantPaymentsByMerchantByDate.GetMerchantPaymentsByMerchantByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/merchant-payments-by-merchant-by-date?merchant_id={{merchantId}}&from_date={{fromDate}}&to_date={{toDate}}'

### io.aggregator.view.MerchantPaymentsAll.GetMerchantPaymentsAll

GET {{urlPrefix}}/merchant-payments-all HTTP/1.1
Content-Type: application/json
