
# HTTP requests used with VS Code REST Client extension

@urlPrefix = https://sweet-scene-6700.eu-central-1.kalix.app
@merchantId = merchant-1
@serviceCode = service-code-1
@accountFrom = account-from-1
@accountTo = account-to-1

### io.aggregator.api.Merchant.MerchantAggregationRequest

curl -XPOST -H "Content-Type: application/json" -d '{
  "merchant_id":"{{merchantId}}",
  "service_code":"{{serviceCode}}",
  "account_from":"{{accountFrom}}",
  "account_to":"{{accountTo}}"}'
  {{urlPrefix}}/merchant/aggregation-request

### io.aggregator.api.Merchant.MerchantPaymentRequest

POST {{urlPrefix}}/merchant/payment-request
Content-Type: application/json

{
  "merchant_id":"{{merchantId}}",
  "service_code":"{{serviceCode}}",
  "account_from":"{{accountFrom}}",
  "account_to":"{{accountTo}}"
}

### io.aggregator.api.Merchant.GetHerchand

GET {{urlPrefix}}/merchant HTTP/1.1
Content-Type: application/json

{
  "merchant_id":"{{merchantId}}",
  "service_code":"{{serviceCode}}",
  "account_from":"{{accountFrom}}",
  "account_to":"{{accountTo}}"
}
