
# Curl commands used with VS Code REST Client extension

@urlPrefix = https://sweet-scene-6700.eu-central-1.kalix.app
@paymentId = payment-1
@merchantId = merchant-1
@serviceCode = service-code-1
@accountFrom = account-from-1
@accountTo = account-to-1
@fromDate = 2022-03-09T00:00:00.000Z
@toDate = 2023-01-01T00:00:00.000-00:00
@offset = 260
@limit = 10

### io.aggregator.view.TransactionsPaidByPaymentByDate.GetTransactionsPaidByPaymentByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/transactions-paid-by-payment-by-date?payment_id={{paymentId}}&merchant_id={{merchantId}}&service_code={{serviceCode}}&account_from={{accountFrom}}&account_to={{accountTo}}&from_date={{fromDate}}&to_date={{toDate}}&transaction_offset={{offset}}&transaction_limit={{limit}}'

### io.aggregator.view.TransactionsNotPaidByDate.GetTransactionsNotPaidByDate

curl -XGET -H "Content-Type: application/json"
  '{{urlPrefix}}/transactions-not-paid-by-date?from_date={{fromDate}}&to_date={{toDate}}&transaction_offset={{offset}}&transaction_limit={{limit}}'
